### ISSUE TITLE
DCP generation fails for some tests

### ISSUE THREAD

**Issue by acomodi** [chipsalliance/fpga-interchange-tests#106]
Upon updating the RapidWright version containing the fix for https://github.com/chipsalliance/fpga-interchange-tests/issues/94, some tests started to fail at the DCP generation from the physical and logical netlists in RapidWright.

These tests were not failing earlier and there was no change in the toolchain, therefore it might be caused by changes in RapidWright.

### Steps to reproduce

1. Download [murax.zip](https://github.com/chipsalliance/fpga-interchange-tests/files/8288461/murax.zip)
2. `unzip murax.zip`
3. `cd murax && RAPIDWRIGHT_PATH=<path to RW> make`

This should output the following:

```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at com.xilinx.rapidwright.util.ParallelismTools.joinFirst(ParallelismTools.java:221)
        at b.b(Unknown Source)
        at b.a(Unknown Source)
        at com.xilinx.rapidwright.design.Design.writeCheckpoint(Unknown Source)
        at com.xilinx.rapidwright.interchange.PhysicalNetlistToDcp.main(PhysicalNetlistToDcp.java:69)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.xilinx.rapidwright.util.ParallelismTools.joinFirst(ParallelismTools.java:219)
        ... 4 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at com.xilinx.rapidwright.util.ParallelismTools.get(ParallelismTools.java:149)
        at com.xilinx.rapidwright.util.ParallelismTools.join(ParallelismTools.java:244)
        at S.a(Unknown Source)
        at b.a(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.xilinx.rapidwright.util.ParallelismTools.get(ParallelismTools.java:147)
        ... 7 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at com.xilinx.rapidwright.util.ParallelismTools.joinFirst(ParallelismTools.java:221)
        at S.a(Unknown Source)
        at S.a(Unknown Source)
        at com.xilinx.rapidwright.util.b.a(Unknown Source)
        at S.a(Unknown Source)
        ... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.xilinx.rapidwright.util.ParallelismTools.joinFirst(ParallelismTools.java:219)
        ... 8 more
Caused by: java.lang.NullPointerException
        at com.xilinx.rapidwright.device.Node.a(Unknown Source)
        at S.a(Unknown Source)
        at S.a(Unknown Source)
        at S.a(Unknown Source)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        ... 7 more
```

### Versions

RapidWright: 57ffdef175dd669d66fb0a1d0261b888e64c48b6

**Comment by acomodi** [comment]
> Testcase link not currently working.

@eddieh-xlnx I think there was an issue with GH, I have uploaded a new zip which should work now

**Comment by eddieh-xlnx** [comment]
Thanks! The issue should be fixed with the latest RapidWright, can you please give that a try?

**Comment by acomodi** [comment]
@eddieh-xlnx Bumping RW fixed the problem, thanks for the quick fix! Closing.
